export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  TOGGLE_SEARCH: "TOGGLE_SEARCH",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  SHOW_TOAST_NOTIFY: "SHOW_TOAST_NOTIFY",
};